-- CareMarket initial Supabase PostgreSQL schema
-- Scope: schema only. No RLS policies, auth triggers, or seed data.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'user'
    check (role in ('user', 'admin')),
  primary_goal text
    check (
      primary_goal in (
        'muscle_gain',
        'weight_control',
        'nutrition_management',
        'supplement_search'
      )
    ),
  created_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  preference_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  low_sugar boolean not null default false,
  low_sodium boolean not null default false,
  high_protein boolean not null default false,
  exclude_caffeine boolean not null default false,
  excluded_allergens text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_user_id_unique unique (user_id)
);

create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  price integer not null check (price >= 0),
  original_price integer check (original_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  summary text,
  serving_size text,
  calories numeric(10, 2) not null default 0 check (calories >= 0),
  protein numeric(10, 2) not null default 0 check (protein >= 0),
  carbs numeric(10, 2) check (carbs >= 0),
  fat numeric(10, 2) check (fat >= 0),
  sugar numeric(10, 2) not null default 0 check (sugar >= 0),
  sodium numeric(10, 2) not null default 0 check (sodium >= 0),
  allergens text[] not null default '{}',
  contains_caffeine boolean not null default false,
  main_ingredients text[] not null default '{}',
  is_active boolean not null default true,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  cart_item_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  product_id bigint not null references public.products(product_id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cart_items_user_product_unique unique (user_id, product_id)
);

create table if not exists public.orders (
  order_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(user_id) on delete restrict,
  toss_order_id text unique,
  payment_key text unique,
  total_price integer not null check (total_price >= 0),
  status text not null default 'pending'
    check (
      status in (
        'pending',
        'paid',
        'preparing',
        'shipped',
        'delivered'
      )
    ),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  order_item_id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(order_id) on delete cascade,
  product_id bigint not null references public.products(product_id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price_at_order integer not null check (price_at_order >= 0)
);

create index if not exists user_preferences_user_id_idx
  on public.user_preferences(user_id);

create index if not exists products_category_idx
  on public.products(category);

create index if not exists cart_items_user_id_idx
  on public.cart_items(user_id);

create index if not exists cart_items_product_id_idx
  on public.cart_items(product_id);

create index if not exists orders_user_id_created_at_idx
  on public.orders(user_id, created_at desc);

create index if not exists order_items_order_id_idx
  on public.order_items(order_id);

create index if not exists order_items_product_id_idx
  on public.order_items(product_id);
